### ISSUE TITLE
Make a waffle wall

### ISSUE THREAD

**Issue by AdrieanKhisbe** [skuro/org4idea#3]
Hey @skuro, could you add me as *Collaborator*,

so that we can open a waffle board, and so I can have access to label and milestone, to give a better idea of the current development I am doing. (which has stalled for the last two weeks behing focused on other project)

Thanks in advance :)

**Comment by skuro** [comment]
You got it!

**Comment by AdrieanKhisbe** [comment]
Thaaaanks :) :+1:
