### ISSUE TITLE
Update Org⁴Idea to latests build

### ISSUE THREAD

**Issue by jamiguet** [skuro/org4idea#4]
When installing the latest release 0.4.0 on  IntelliJ IDEA 2017.1.3
Build #IU-171.4424.56, built on May 12, 2017

It states that the plugin is not supported as the version requirements do not match.
Is only repackaging necessary or have the APIs changed significantly.

**Comment by skuro** [comment]
Good question. I'll have to look into it, thanks for reporting the issue

**Comment by jamiguet** [comment]
Hi, 

Did you have time to check?

Many thanks in advance.

**Comment by plewin** [comment]
Only repackaging is necessary.

I added `updateSinceUntilBuild false` to gradle here

https://github.com/skuro/org4idea/blob/389cfa1cc92c3ea97edd37925a54467af4e1d999/build.gradle#L15

And now it builds a compatible plugin, the plugin works fine on my intellij 2018.1.1

Doc of updateSinceUntilBuild :
https://github.com/JetBrains/intellij-sdk-docs/blob/master/tutorials/build_system/deployment.md#21-configure-your-plugin

**Comment by skuro** [comment]
@plewin the warning might be unrelated. Care to put together a PR with your changes?

**Comment by jamiguet** [comment]
Awesome thanks !!!
Just updated and it works.
